sudo: required
services:
  - docker

before_install:
  - docker build -t bogertron/docker-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true bogertron/docker-travis npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "travis-docker"
  env: "TravisDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-083487392674"
  bucket_path: "travis-docker"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"